import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
	container: {
		marginBottom: 32,
		paddingHorizontal: 16,
	},
	pressable: {
		width: '100%',
	},
	card: {
		backgroundColor: '#fff',
		borderRadius: 32,
		paddingTop: 40,
		paddingHorizontal: 20,
		paddingBottom: 32,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 10 },
		shadowOpacity: 0.1,
		shadowRadius: 20,
		elevation: 15,
		overflow: 'hidden',
	},
	bgCircle: {
		position: 'absolute',
		top: -120,
		left: -120,
		width: width + 200,
		height: width + 200,
		borderRadius: (width + 200) / 2,
		backgroundColor: '#E6F0FF',
		opacity: 0.8,
	},
	avatarContainer: {
		alignItems: 'center',
		marginBottom: 20,
	},
	avatar: {
		width: 140,
		height: 140,
		borderRadius: 70,
		borderWidth: 6,
		borderColor: '#fff',
	},
	ratingBadge: {
		position: 'absolute',
		top: 8,
		left: 8,
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#fff',
		paddingHorizontal: 12,
		paddingVertical: 8,
		borderRadius: 24,
		shadowColor: '#000',
		shadowOpacity: 0.15,
		shadowRadius: 8,
		elevation: 10,
	},
	starIcon: {
		width: 18,
		height: 18,
		marginRight: 6,
	},
	ratingText: {
		fontFamily: 'Hezaedrus500',
		fontSize: 15,
		color: '#3565D9',
	},
	favoriteButton: {
		position: 'absolute',
		top: 8,
		right: 8,
		backgroundColor: '#fff',
		padding: 10,
		borderRadius: 30,
		shadowColor: '#000',
		shadowOpacity: 0.15,
		shadowRadius: 8,
		elevation: 10,
	},
	heartIcon: {
		width: 25,
		height: 25,
	},
	info: {
		alignItems: 'center',
	},
	name: {
		fontFamily: 'Hezaedrus500',
		fontSize: 22,
		color: '#011443',
		marginBottom: 6,
		textAlign: 'center',
	},
	methods: {
		fontFamily: 'Hezaedrus',
		fontSize: 15,
		color: '#01144399',
		marginBottom: 20,
		textAlign: 'center',
	},
	priceRow: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: 28,
	},
	priceLabel: {
		fontFamily: 'Hezaedrus',
		fontSize: 18,
		color: '#01144380',
		margin: 8,
	},
	price: {
		fontFamily: 'Hezaedrus500',
		fontSize: 26,
		color: '#011443',
	},
	currency: {
		fontFamily: 'Hezaedrus500',
		fontSize: 20,
		color: '#011443',
		marginLeft: 4,
	},
	infoBadge: {
		marginLeft: 10,
		backgroundColor: '#E6F0FF',
		width: 24,
		height: 24,
		borderRadius: 12,
		justifyContent: 'center',
		alignItems: 'center',
	},
	infoText: {
		fontSize: 16,
		color: '#011443',
		fontWeight: 'bold',
	},
	stats: {
		flexDirection: 'row',
		gap: 16,
		marginBottom: 32,
	},
	statItem: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#f1f4fbff',
		paddingHorizontal: 16,
		paddingVertical: 12,
		borderRadius: 28,
	},
	statIcon: {
		width: 22,
		height: 22,
	},
	statText: {
		fontFamily: 'Hezaedrus500',
		fontSize: 14,
		color: '#4163B8',
	},
	bookButton: {
		backgroundColor: '#3E75FF',
		paddingHorizontal: 52,
		paddingVertical: 18,
		borderRadius: 32,
	},
	bookButtonText: {
		fontFamily: 'Hezaedrus500',
		fontSize: 17,
		color: '#fff',
	},
	flagButton: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#3E75FF',
		width: 35,
		height: 35,
		borderRadius: '50%',
		marginRight: 10,
	},
	modalOverlay: {
		flex: 1,
		backgroundColor: 'rgba(0,0,0,0.5)',
		justifyContent: 'center',
		alignItems: 'center',
	},
	modalBox: {
		backgroundColor: '#fff',
		borderRadius: 20,
		padding: 20,
		width: '85%',
	},
	modalTitle: {
		fontFamily: 'Hezaedrus500',
		fontSize: 18,
		textAlign: 'center',
		marginBottom: 16,
		color: '#011443',
	},
	modalInput: {
		borderWidth: 1,
		borderColor: '#ddd',
		borderRadius: 12,
		paddingVertical: 12,
		paddingHorizontal: 16,
		fontSize: 16,
		color: '#011443',
		marginBottom: 20,
	},
	modalButtonsRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
	},
	modalBtn: {
		backgroundColor: '#eee',
		paddingHorizontal: 24,
		paddingVertical: 12,
		borderRadius: 20,
	},
	modalBtnPrimary: {
		backgroundColor: '#3E75FF',
		paddingHorizontal: 24,
		paddingVertical: 12,
		borderRadius: 20,
	},
	modalBtnText: {
		fontFamily: 'Hezaedrus500',
	},
	modalBtnPrimaryText: {
		fontFamily: 'Hezaedrus500',
		color: '#fff',
	},
});
