import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	container: {
		width: '100%',
		height: '100%',
		paddingLeft: 16,
		paddingRight: 16,
	},
	container__header: {
		width: '100%',
		height: 'auto',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		marginTop: 30,
	},
	container__avatar: {
		height: 100,
		width: 100,
		backgroundColor: '#d1d1d1',
		borderRadius: 100,
	},
	container__text: {
		fontFamily: 'Hezaedrus500',
		color: '#3565D9',
		marginTop: 12,
		fontSize: 16,
	},
	container__body: {
		width: '100%',
		height: '100%',
		position: 'relative',
		marginTop: 40,
	},
	container__inputs: {
		width: '100%',
		backgroundColor: '#fff',
		height: 158,
		borderRadius: 12,
		position: 'relative',
		paddingLeft: 0,
		paddingRight: 0,
	},
	phone__input: {
		width: '100%',
		position: 'relative',
		height: 'auto',
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
	},
	input: {
		height: 50,
		width: '100%',
		backgroundColor: 'transparent',
		fontFamily: 'Hezaedrus500',
	},
	input__code: {
		position: 'absolute',
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		borderWidth: 1,
		borderColor: 'rgba(1, 20, 67, 0.1)',
		height: 24,
		paddingLeft: 3,
		paddingRight: 3,
		borderRadius: 4,
		left: 16,
		zIndex: 10,
	},
	code__image: {
		height: 14,
		width: 14,
	},
	select__wrap: {
		backgroundColor: '#fff',
		marginTop: 20,
		borderRadius: 12,
	},
	select: {
		marginVertical: 0,
		borderColor: 'transparent',
	},
	code__text: {
		fontFamily: 'Hezaedrus500',
		fontSize: 14,
		marginLeft: 5,
	},
	label__style: {
		paddingTop: 0,
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		borderBottomWidth: 1,
		borderBottomColor: 'rgba(1, 20, 67, 0.1)',
		paddingLeft: 16,
		paddingRight: 16,
	},
	next__button: {
		backgroundColor: '#3871FF',
		height: 50,
		width: '100%',
		borderRadius: 50,
		position: 'absolute',
		bottom: 270,
		alignItems: 'center',
		justifyContent: 'center',
	},
	button__text: {
		color: '#fff',
		fontFamily: 'Hezaedrus',
		fontSize: 14,
	},
	selectContainer: {
		width: '100%',
		paddingLeft: 2,
		paddingRight: 2,
		marginTop: 0,
		borderWidth: 0,
	},
});
