"""psychologist_optional_fields

Revision ID: 01716be242f6
Revises: 3904bfb88db9
Create Date: 2026-01-19 23:29:27.368428

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01716be242f6"
down_revision: Union[str, Sequence[str], None] = "3904bfb88db9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "psychologist_profiles", "first_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "psychologist_profiles", "last_name", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "psychologist_profiles", "last_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "psychologist_profiles",
        "first_name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
