"""user_favorites_cascade

Revision ID: 0449aca9e009
Revises: a30f980801a9
Create Date: 2026-01-19 16:36:36.732295

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0449aca9e009"
down_revision: Union[str, Sequence[str], None] = "a30f980801a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("user_favorites_user_id_fkey"), "user_favorites", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "user_favorites",
        "client_profiles",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_favorites", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_favorites_user_id_fkey"),
        "user_favorites",
        "client_profiles",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
