"""favorites

Revision ID: 1108c89d7d9c
Revises: 345df63f403e
Create Date: 2025-11-01 01:38:44.238815

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1108c89d7d9c"
down_revision: Union[str, Sequence[str], None] = "345df63f403e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_favorites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("psychologist_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["psychologist_id"],
            ["psychologist_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["client_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "psychologist_id", name="uq_favorites_user_psychologist"
        ),
    )
    op.add_column(
        "psychologist_profiles", sa.Column("first_name", sa.String(), nullable=False)
    )
    op.add_column(
        "psychologist_profiles", sa.Column("last_name", sa.String(), nullable=False)
    )
    op.add_column(
        "psychologist_profiles", sa.Column("avatar", sa.String(), nullable=True)
    )
    op.add_column(
        "psychologist_profiles",
        sa.Column(
            "methods",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("psychologist_profiles", "methods")
    op.drop_column("psychologist_profiles", "avatar")
    op.drop_column("psychologist_profiles", "last_name")
    op.drop_column("psychologist_profiles", "first_name")
    op.drop_table("user_favorites")
    # ### end Alembic commands ###
