"""payment_methods

Revision ID: 345df63f403e
Revises: 5543f4815159
Create Date: 2025-10-23 17:59:25.924677

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "345df63f403e"
down_revision: Union[str, Sequence[str], None] = "5543f4815159"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_methods",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("SBP", name="paymentmethodtype"), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("bank", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_methods_phone"), "payment_methods", ["phone"], unique=False
    )
    op.create_index(
        op.f("ix_payment_methods_user_id"), "payment_methods", ["user_id"], unique=False
    )
    op.drop_constraint(
        op.f("admin_profiles_id_fkey"), "admin_profiles", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "admin_profiles", "users", ["id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("client_profiles_id_fkey"), "client_profiles", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "client_profiles", "users", ["id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("psychologist_profiles_id_fkey"),
        "psychologist_profiles",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "psychologist_profiles", "users", ["id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "psychologist_profiles", type_="foreignkey")
    op.create_foreign_key(
        op.f("psychologist_profiles_id_fkey"),
        "psychologist_profiles",
        "users",
        ["id"],
        ["id"],
    )
    op.drop_constraint(None, "client_profiles", type_="foreignkey")
    op.create_foreign_key(
        op.f("client_profiles_id_fkey"), "client_profiles", "users", ["id"], ["id"]
    )
    op.drop_constraint(None, "admin_profiles", type_="foreignkey")
    op.create_foreign_key(
        op.f("admin_profiles_id_fkey"), "admin_profiles", "users", ["id"], ["id"]
    )
    op.drop_index(op.f("ix_payment_methods_user_id"), table_name="payment_methods")
    op.drop_index(op.f("ix_payment_methods_phone"), table_name="payment_methods")
    op.drop_table("payment_methods")
    # ### end Alembic commands ###
