"""psychologist_columns

Revision ID: 3904bfb88db9
Revises: 0449aca9e009
Create Date: 2026-01-19 17:15:45.689130

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3904bfb88db9"
down_revision: Union[str, Sequence[str], None] = "0449aca9e009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "psychologist_profiles",
        sa.Column("rating", sa.Float(), server_default="0", nullable=False),
    )
    op.add_column(
        "psychologist_profiles", sa.Column("experience", sa.Integer(), nullable=True)
    )
    op.add_column(
        "psychologist_profiles", sa.Column("price", sa.Integer(), nullable=True)
    )
    op.add_column(
        "psychologist_profiles", sa.Column("age", sa.Integer(), nullable=True)
    )
    op.add_column(
        "psychologist_profiles",
        sa.Column(
            "gender",
            sa.Enum("NOT_STATED", "MALE", "FEMALE", name="usergender"),
            server_default="NOT_STATED",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("psychologist_profiles", "gender")
    op.drop_column("psychologist_profiles", "age")
    op.drop_column("psychologist_profiles", "price")
    op.drop_column("psychologist_profiles", "experience")
    op.drop_column("psychologist_profiles", "rating")
    # ### end Alembic commands ###
