"""add client_notes table

Revision ID: 9712b1db3b73
Revises: 01716be242f6
Create Date: 2026-04-25 00:44:41.229120

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9712b1db3b73"
down_revision: Union[str, Sequence[str], None] = "01716be242f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("psychologist_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["psychologist_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_notes_client_id"), "client_notes", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_client_notes_psychologist_id"),
        "client_notes",
        ["psychologist_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_client_notes_psychologist_id"), table_name="client_notes")
    op.drop_index(op.f("ix_client_notes_client_id"), table_name="client_notes")
    op.drop_table("client_notes")
    # ### end Alembic commands ###
