"""user

Revision ID: c674b9a1b942
Revises:
Create Date: 2025-10-18 15:47:44.323940

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c674b9a1b942"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("CLIENT", "PSYCHOLOGIST", "ADMIN", name="userrole"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "admin_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "client_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_new", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column(
            "gender",
            sa.Enum("NOT_STATED", "MALE", "FEMALE", name="usergender"),
            nullable=False,
        ),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("notifications", sa.Boolean(), nullable=False),
        sa.Column(
            "timezone",
            sa.Enum(
                "UTC_12_M",
                "UTC_11_M",
                "UTC_10_M",
                "UTC_9_M",
                "UTC_8_M",
                "UTC_7_M",
                "UTC_6_M",
                "UTC_5_M",
                "UTC_4_M",
                "UTC_3_M",
                "UTC_2_M",
                "UTC_1_M",
                "UTC",
                "UTC_1_P",
                "UTC_2_P",
                "UTC_3_P",
                "UTC_4_P",
                "UTC_5_P",
                "UTC_6_P",
                "UTC_7_P",
                "UTC_8_P",
                "UTC_9_P",
                "UTC_10_P",
                "UTC_11_P",
                "UTC_12_P",
                "UTC_13_P",
                "UTC_14_P",
                name="usertimezone",
            ),
            nullable=True,
        ),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("emotions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("relations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("work", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("life", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("personal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("format", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_client_profiles_phone"), "client_profiles", ["phone"], unique=True
    )
    op.create_table(
        "psychologist_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("psychologist_profiles")
    op.drop_index(op.f("ix_client_profiles_phone"), table_name="client_profiles")
    op.drop_table("client_profiles")
    op.drop_table("admin_profiles")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
