import { StyleSheet } from 'react-native';
import { UI } from '@/types/ui';

export const styles = StyleSheet.create({
	container: {
		width: '100%',
		height: '100%',
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'space-between',
		backgroundColor: '#f8f9fd',
	},
	container__header: {
		width: '100%',
		display: 'flex',
		height: 44,
		position: 'absolute',
		top: 60,
		flexDirection: 'row',
		justifyContent: 'center',
		alignItems: 'center',
	},
	header__title: {
		color: '#011443',
		fontFamily: 'Hezaedrus500',
		fontSize: 18,
		fontWeight: 'medium',
	},
	back__btn: {
		position: 'absolute',
		left: 16,
		height: 44,
		width: 44,
		borderRadius: 100,
		borderWidth: 1,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		borderColor: '#1A011443',
	},
	code__container: {
		width: '100%',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		paddingLeft: 16,
		paddingRight: 16,
	},
	code__title: {
		color: '#011443',
		fontFamily: 'Hezaedrus500',
		fontSize: 20,
		fontWeight: 'medium',
	},
	code__description: {
		textAlign: 'center',
		fontFamily: 'Hezaedrus',
		color: '#01144366',
		marginTop: 8,
		width: 306,
	},
	code__timer: {
		fontSize: 16,
		color: '#10316B',
	},
	input__wrap: {
		width: '100%',
		display: 'flex',
		flexDirection: 'row',
		height: 52,
		gap: 16,
		justifyContent: 'center',
		marginTop: 20,
	},
	input: {
		height: 52,
		width: 52,
		borderRadius: 12,
		borderWidth: 1.5,
		paddingLeft: 20,
		fontFamily: 'Hezaedrus500',
		borderColor: '#D3E0FF',
		color: '#3565D9',
		fontSize: 20,
	},
	repeat__text: {
		marginTop: 20,
		fontSize: 16,
		fontFamily: 'Hezaedrus',
		color: '#01144366',
	},
	input__active: {
		borderColor: UI.colors.blue,
	},
	next__button: {
		backgroundColor: '#3871FF',
		height: 50,
		width: '80%',
		borderRadius: 50,
		alignItems: 'center',
		justifyContent: 'center',
		marginTop: 20,
	},
	button__text: {
		color: '#fff',
		fontFamily: 'Hezaedrus500',
		fontSize: 14,
	},
	container__error: {
		marginTop: 20,
		fontFamily: 'Hezaedrus',
		color: 'red',
	},
});
