export const meditationItems = [
	{
		id: 1,
		title: 'От тревоги',
		emoji: require('@/assets/images/flash.png'),
		color: '#FAEEE8',
		duration: '6 минут 14 секунд',
		bgImage: require('@/assets/images/sunset.jpg'),
		audio: require('@/assets/audio/anxiety_relief.mp3'),
	},
	{
		id: 2,
		title: 'Для крепкого сна',
		emoji: require('@/assets/images/moon.png'),
		color: '#E4F2F4',
		duration: '8 минут 36 секунд',
		bgImage: require('@/assets/images/night_sky.jpg'),
		audio: require('@/assets/audio/deep_sleep.mp3'),
	},
	{
		id: 3,
		title: 'Расслабление',
		emoji: require('@/assets/images/heart.png'),
		color: '#DFF6FF',
		duration: '13 минут 42 секунды',
		bgImage: require('@/assets/images/waves.jpg'),
		audio: require('@/assets/audio/relaxation.mp3'),
	},
	{
		id: 4,
		title: 'Снятие стресса',
		emoji: require('@/assets/images/sad.png'),
		color: '#F2E7FF',
		duration: '6 минут 11 секунд',
		bgImage: require('@/assets/images/forest.jpg'),
		audio: require('@/assets/audio/stress_relief.mp3'),
	},
	{
		id: 5,
		title: 'Звуки природы',
		emoji: require('@/assets/images/cloud.png'),
		color: '#E1F6EB',
		duration: '10 минут',
		bgImage: require('@/assets/images/grass.jpg'),
		audio: require('@/assets/audio/nature_sounds.mp3'),
	},
	{
		id: 6,
		title: 'Фокус на работе',
		emoji: require('@/assets/images/briefcase_meditation.png'),
		color: '#E9EEF9',
		duration: '6 минут 15 секунд',
		bgImage: require('@/assets/images/mountain.jpg'),
		audio: require('@/assets/audio/focus_music.mp3'),
	},
];
